### ISSUE TITLE
GitHub Actions setting wrong version even with `fetch-depth` 

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [ajoberstar/reckon#157]
Using this + debugging Gradle

```
name: "Checkout repo"
uses: "actions/checkout@v2"
  with:
    fetch-depth: 0
``` 

Let me know that Reckon knows that there is a tag, but for some reason, it is not setting the same version as in local.
