### ISSUE TITLE
Cron builds in Github Actions result in `Scope between bases` error

### ISSUE THREAD

**Issue by snowe2010** [ajoberstar/reckon#203]
When running a scheduled github action (cron) with the last tag being an `rc`, we get the failure:

```
* What went wrong:
A problem occurred configuring root project 'tax-service'.
> Could not determine the dependencies of null.
   > Could not resolve all dependencies for configuration ':classpath'.
      > Failed to calculate the value of extension 'reckon' property 'version'.
         > Scope between bases 0.0.0 and 1.0.1-rc.1 must be same or 1 MAJOR/MINOR/PATCH increment apart and are not. Cannot determine correct action.
```

Running this _locally_ with the same parameters, we get no such error. Locally the base is chosen as `1.0.0` correctly. Reckon doesn't have any logs in this area explaining why 0.0.0 was chosen, but you can see in debug mode that `1.0.0` does exist

```
2024-07-15T19:28:18.320+0000 [DEBUG] [org.ajoberstar.reckon.core.Reckoner] Retrieved the following VCS inventory: VcsInventory[baseNormal=0.0.0,baseVersion=1.0.1-rc.2,claimedVersions=[0.0.2-rc.20, 0.0.2-rc.21, 0.0.2-rc.22, 0.0.2-rc.23, 1.0.1-rc.1, 0.0.2-rc.1, 0.0.2-rc.2, 1.0.1-rc.2, 0.0.2-rc.3, 0.0.2-rc.4, 0.0.2-rc.5, 0.0.2-rc.6, 0.0.2-rc.7, 0.0.2-rc.8, 0.0.2-rc.9, 0.0.2-rc.10, 0.0.2-rc.11, 0.0.2-rc.12, 0.0.2-rc.13, 0.0.2-rc.14, 0.0.2-rc.15, 1.0.0, 0.0.2-rc.16, 0.0.1, 0.0.2-rc.17, 0.0.2-rc.18, 0.0.2-rc.19],clean=true,commitId=6fcd9cc,commitMessages=[Turn on debug mode for reckon (#145)

],commitsSinceBase=1,currentVersion=1.0.1-rc.2,parallelNormals=[]]
```

Our settings:

```kotlin
setDefaultInferredScope("patch")
stages("rc", "final")
setScopeCalc(calcScopeFromProp().or(calcScopeFromCommitMessages()))
setStageCalc(calcStageFromProp())
```

If I create a final tag then the error goes away in github actions. This still doesn't explain why it works perfectly fine locally but not in GHA. 

Simplified GH Workflow:

```yaml
name: "build"
on:
  schedule:
    - cron: "3/20 * * * *"

jobs:
  live:
    name: "run live tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: "true"

# ...
      - name: build
        run: ./gradlew build --debug
# ...
```
